// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi119fTPq_N9e40yZO2UWJSSpY_0_X0oE',
    appId: '1:585513202736:web:1b64f7bb864b1a26f4e9f5',
    messagingSenderId: '585513202736',
    projectId: 'managercarios',
    authDomain: 'managercarios.firebaseapp.com',
    storageBucket: 'managercarios.appspot.com',
    measurementId: 'G-1M2RYFHBHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEM0g6B19BkW66juvHRK9dxOl-A-jxIYM',
    appId: '1:585513202736:android:7766328ffdef6759f4e9f5',
    messagingSenderId: '585513202736',
    projectId: 'managercarios',
    storageBucket: 'managercarios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIG8F8-vv33Ku4lCsXQ8eJwr9IdwPK99M',
    appId: '1:585513202736:ios:a3eee2888c66bca6f4e9f5',
    messagingSenderId: '585513202736',
    projectId: 'managercarios',
    storageBucket: 'managercarios.appspot.com',
    iosBundleId: 'com.example.managerCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIG8F8-vv33Ku4lCsXQ8eJwr9IdwPK99M',
    appId: '1:585513202736:ios:6fafaa997d013837f4e9f5',
    messagingSenderId: '585513202736',
    projectId: 'managercarios',
    storageBucket: 'managercarios.appspot.com',
    iosBundleId: 'com.example.managerCar.RunnerTests',
  );
}
